### ISSUE TITLE
Work with GTRI to deploy Application on Geoplatform

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/cbrsdms#166]

**Comment by HansVraga** [comment]
We heard back from Gale that an account was set up, but have we heard anything from their engineering folks @aaronstephenson ?

**Comment by aaronstephenson** [comment]
No. I just sent an email asking about it.

**Comment by HansVraga** [comment]
@aaronstephenson was going to open an issue to track the effort to have an environment ready for use, but see we already have one. So, just a reminder that we're scheduled to migrate next week - so should revisit this in preparation.

**Comment by HansVraga** [comment]
Completed!
