### ISSUE TITLE
Cases by Unit Report 

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/cbrsdms#181]
Requested Enhancement to the Cases by Unit Report:
>Please add the following fields to the report:
"Case Reference" (add after Case ID)
"City" (add after Street Address)
"Duplicate of" (add after Street Address and City)

Note from Aaron:
>fields added to the API endpoint

**Comment by aaronstephenson** [comment]
@HansVraga do you remember if this ever got resolved? Or should it be included in Phase II work?

**Comment by HansVraga** [comment]
I don't remember - I figured if @kjacobsen16 gets through all the stuff Paul asked for, she can take a look at some of these older issues to see if they are redundant/necessary/already done
