### ISSUE TITLE
Case Duplication improvements

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/cbrsdms#194]
Request from cooperator
>Duplicate case logic:  Remove logic that populates data from seed case to duplicate case.  There are many times where the information is different than the seed case.  Right now it overwrites changes e.g. requester name or policy number.
>
>Add Case Id at top of dropdown menu to make it clear that the list is case ids not reference numbers.

**Comment by kjacobsen16** [comment]
Aaron and I were unable to replicate the issue, we will need some more info from cooperator

**Comment by kjacobsen16** [comment]
Paul and his team were also unable to replicate, closing issue.
