### ISSUE TITLE
Authorization issues

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/cbrsdms#213]
We had some weird user permissions issues where someone got errors editing her password but the password was changed anyway. There was some missing checkboxes as well (that weren't showing up until she logged out/back in)

I think one possibility is that her authorization had expired. I'm not sure the best way to check for that, maybe we can check for expired creds if an error comes back or check them before sending authentication through with a call?

There should maybe be more testing done in case there was more than just that going on.

**Comment by aaronstephenson** [comment]
I am not able to reproduce this on my local dev environment or on the test server.

**Comment by HansVraga** [comment]
Unless I'm mis-reading an email thread, this is resolved.
